### PR TITLE
Update feat.2da rows for Mysteries of Westgate

### PR DESCRIPTION
**Pull request by NinjaSpectre**
This feat.2da differs from the stock file in the Westgate campaign by having rows #1088 and #1089 swapped (which is the previous Tiefling feat fix by Pain of Dungeon Eternal) and having an additional "Instant" column.

### CODE REVIEW

**Comment by kevL** [comment]
(i don't have Westgate) it just adds in new feats from Westgate?

**Comment by NinjaSpectre** [comment]
Right.  For whatever reasons Ossian has the following 9 .2da files in their campaign folder:
- ambientmusic
- appearance
- feat
- nwn2_icons
- placeables
- polymorph
- soundset
- spells
- wingmodel

**Comment by kevL** [comment]
ok. As long as nwn2fixes doesn't tweak any of the other base 2das, we're compatible so far.

thanks, Ninja

**Comment by NinjaSpectre** [comment]
I just found this while looking at the [Ossian Studios Mysteries of Westgate site](http://www.ossianstudios.com/mow).  They provide a [.zip download for the .2da files](http://www.ossianstudios.com/downloads/NWN2_MoW_2DA_FilesForSoZ.zip) if you care to look at them yourself.

**Comment by kevL** [comment]
tks

**Pull request merged**
