### PR TITLE
Add info about install to Readme

### PR DESCRIPTION
**Pull request by pianoslum**
Had to look it up, so it might be useful for others as well ;)

### CODE REVIEW

**Comment by Clangeddin** [comment]
I'd like to suggest a change to the installation path,
considering that NWN2fixes is supposed to be a collection of changes to the stock resources, shouldn't it be installed in Override folder of the NWN2 installation folder instead?
Since it has a lower priority than the ones in My Documents, It would improve compatibility with other mods imho, reducing the risk of conflicts.
It's what I have done in my setup and I'm not having any problems so far.

**Comment by pianoslum** [comment]
I copied the info from https://neverwintervault.org/project/nwn2/other/patch/nwn2-fixes

Honestly, I don't know which is better, maybe @kevL can decide? :)

**Comment by kevL** [comment]
hey guys,

I'm going to pull this as-is at the moment

@Clangeddin That sounds like a good idea ... the only quirk I see, though, and uh yeah this is subjective, is two things

- placing custom content in the installation folders is generally agreed to be a no-go. I mean, you me and another guy can deal with this like it's a no-brainer perhaps ... but i could see it leading to moments of confusion

- secondly, running a duplicate file checker should become common procedure for anyone who tosses stuff into Docs/Override, right? And as long as player-master is kept in Docs/Override this is a simple straightforward check, but would be less so if user should be required to set up his/her duplicate file checker app to run against the docs and the installation folders both ...

Other than those 'concerns' it sounds like a really good idea. Care to make a stronger case for it ...?

**Comment by Clangeddin** [comment]
I don't know how priority is handled by NWN2 when different mods are in the same Override directory and conflict with files under different folders (I never even bothered to investigate to be fair), and I doubt many out there know it.
I'd expect it to be harder to figure out than My Documents > Installation path though.
This would also allow for easier testing against potential conflicts (to see if a bug -or lack of a fix- is caused by the file conflict, or the nwn2 file is not working properly at all).
With this in mind I thought it would actually reduce confusion instead of increasing it.

**Comment by kevL** [comment]
> I don't know how priority is handled by NWN2 when different mods are in the same Override directory and conflict with files under different folders

i don't know either. I think of it as just arbitrary ...

regardless, Good point. A possibility is to simply suggest "install to Installation folder" RECOMMENDED ...

I'm kinda worried about how well/badly users will deal with the changeover, from one location to the other

**Pull request merged**
