### PR TITLE
Hlam dialog and Act 3 cutscene

### PR DESCRIPTION
**Pull request by NinjaSpectre**
10_hlam.DLG
3000_cliententer.NCS
3000_cliententer.NSS
3063_hlam.DLG

### CODE REVIEW

**Comment by NinjaSpectre** [comment]
First a huge thank you for doing this.  It is very much appreciated, and these fixes make the official campaigns so much more enjoyable.  Here is an attempt at making some corrections to a few bugs that I came across in my current play through.
Currently the knighting cutscene fires as soon as one leaves Neverneath provided that the Rod of Never is in the inventory.  This makes for some odd situations, such as Nasher talking to you through a closed door and the Reaver watching patiently along side the Guards.  I changed the script to not look for the Rod of Never and to have the Reaver be hostile.  The cutscene now plays when the Reaver is defeated or when Nasher is talked to.  I tried to make the Guards attack the Reaver but that is not working like I had hoped.  There is still some weirdness with the Nobles walking out during Nasher's speech.
The next thing I had troubles with was Khelgar's Vision Quest, which surprised me a little since it had already been looked at.  Turns out there is a separate dialog script for Act 3, which is almost an exact copy of the previous one.  I tinkered with this and ended up making some more changes to both scripts in order to eliminate some weirdness in them.
When telling Khelgar to be a monk, the order on the check was wrong so you could never succeed (although not really a big problem since that is what he chooses if you let him decide).  The next one is when you leave the conversation before making the final choice.  The entry back into this decision didn't check if Khelgar was with you or if he had already made the choice.  I moved this into the same area as the check for each of the trials, and put condition checks on it to make sure all 3 have been completed before being available.  The last thing I did is set the flag for Khelgar being a monk even though you tell him to stay a warrior.  This is because the Journal states that the quest is finished and I didn't notice any other variable being set for this outcome.  Without this change Khelgar could still become a monk afterwards trough the dialog, but the Journal would not be updated from before.

**Comment by kevL** [comment]
hey Ninja, tks

i'll have a look at this (hopefully i have a save nearby.) Maybe fill some things in that you mention might still be quirky ...


no hurries tho

**Comment by kevL** [comment]
some initial comments ...

I'm not so sure that removing the check for the Rod is a good idea. I don't think it's that bad an idea, either; but from what i've seen so far in the 3000-enter script, things will bug-out even easier with the requirement (party-possession of the Rod) removed (simply because it's one less requirement for the cutscene to start). Plus it could be kinda odd for the "battle of the rod" to end, and Nasher says Great, you have the Rod! if the player doesn't ....

anyway, I'd appreciate it if you could give me a very specific reason why the requirement that the Rod needs-to-be-possessed should be removed.


> I tried to make the Guards attack the Reaver but that is not working like I had hoped.

likely because the reaver is plot (until the door behind the throne is opened), the AI-scripts disallow starting fights with plot critters, (more or less)



hm, the reaver still tried to attack my PC through that door ..... will tinker a  bit.

**Comment by kevL** [comment]
edit: turns out there's issues between factions Hostile and 3000Nasher - they won't fight (unless members of 3000Nasher are changed to Defenders)

ps Nasher is a mofo.

**Comment by NinjaSpectre** [comment]
>I'm not so sure that removing the check for the Rod is a good idea.

I agree with this as well.  I am sure there was a good reason why it was coded that way.  I removed the check because if for some reason the Rod was left in Neverneath, the player can't just go back and retrieve it.
>Plus it could be kinda odd for the "battle of the rod" to end, and Nasher says Great, you have the Rod! if the player doesn't ....

Maybe there is a better way to handle this?  Make the Rod undroppable (like a cursed item)?
>ps Nasher is a mofo.

"Then rather than a knighthood, I'll mark you a wanted criminal, throw you in irons, then pardon you only in exchange for your service."

**Comment by kevL** [comment]
y, it creates big problems if PC drops the rod ...

and it's not so easy to flag it cursed, since it's instanced on Halueth's corpse instead of created. So, let's assume that even if PC does drop the Rod, Nasher et al. recognize it as a "done deed" ...

(could use tag-based script, 'spose)

The battle of the rod is looking/working pretty good now. I just have to insert some code (when the Nasher dialog starts) to set things back to the way the OC expects:

- change Nasher's + guards' faction back to 3000Nasher
- clear combat overrides on Nasher + guards
- set Nasher plot again (give them a full heal also)

done.

https://github.com/nwn2fixes/player/commit/7dc3d043ac91ab90ae4a6c8c01bd562636c7ad7b

**Pull request merged**
