### PR TITLE
Creature scripts

### PR DESCRIPTION
**Pull request by Clangeddin**
Code refactoring with performance improvement of default creatures scripts.
This is mainly achieved by reducing the number of calls of OBJECT_SELF by defining it as a variable once.
Spawn script has some additional refactoring about treasure generation.
Please examine thoroughly before committing.

I also reorganized the folder and moved the nw_e0_default8 script there.

### CODE REVIEW

**Comment by kevL** [comment]
wait a second,

Isn't putting nw_c2_default* scripts in /override going to screw with modules that customize the ai-scripts but (rightly or wrongly, wrongly in my opinion) KEEP THE SAME FILENAMES for those scripts

?

**Comment by Clangeddin** [comment]
Yes, it would, but that is the reason why I installed my NWN2fixes in the installation folder instead of the mydocuments one.
But that's ok if you wanna delete this, perhaps the potential gain is not even worth the risk.

**Comment by kevL** [comment]
at this point i just wanna mull things over ... your installation folder idea is making more & more sense

**Comment by kevL** [comment]
did some testing; install/override has higher priority than campaign or module ...

too risky. Obsidian eg placed an 'nw_c2_default4' script in the Campaign_x2 folder (this change, whether to the install or player override, would ofc overrule their script)

/sighshrug

**Pull request closed without merging**
